4 create database migrations
OriOri-CCP7/oriori pull request #10
Opened 2023-05-29 08:51 UTC by SirrorsMoore1975

Resolves #

### REQUIRED:
- [x] Write the issue number associated with this pull request after "Resolves #"
- [x] Add the correct label for this pull request (you can just use the same label as the associated issue)
- [x] Be sure to share a link to this pull request in Slack/Discord and ask for a review! <3

2023-05-29 09:08 UTC, kappanjoe requested changes
Just some build environment fixes as noted in the comments. Additionally, are these migrations set up to run upon build/deployment?

2023-05-29 09:08 UTC, kappanjoe commented on .env.example
> +DB_PASSWORD=
If we can set up different build environments (see comment on `config/settings.py`), let's add the `DATABASE_URL` variable here as well, please.

2023-05-29 09:11 UTC, SirrorsMoore1975 commented on base/models.py
> +    coordinates = models.PointField(srid=4326) # ID for goggle 4326 PointField(srid=4326)
According to Ikuno, I was told using srid=4326 should give you coordinates in the form of Latitude and Attitude, please check if this is correct.

2023-05-30 11:16 UTC, kappanjoe approved these changes

2023-05-30 11:16 UTC, merged

2023-05-30 11:16 UTC, kappanjoe commented
LGTM!